name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install required system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgl1-mesa-dev libx11-dev libxrandr-dev libxi-dev libxxf86vm-dev libxinerama-dev libxcursor-dev

      # Step 3: Configure the project using CMake
      - name: Configure CMake
        run: |
          cmake -S . -B build

      # Step 4: Build the project
      - name: Build the project
        run: |
          cmake --build build -- -j$(nproc)

      # Step 5: Run tests (if you have tests configured)
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
